version: 2
jobs:
  plan:
    docker:
     - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform plan
      - persist_to_workspace:
          root: /root/project
  apply:
    docker:
     - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: /root/project
      - run: terraform apply -auto-approve

workflows:
  version: 2
  validate_infra:
    jobs:
      - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master
