version: 2
jobs:
  plan:
    docker:
     - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: mkdir tfplan_dir
      - run: terraform init
      - run: terraform plan -out=tfplan_dir/tfplan
      - persist_to_workspace:
          root: tfplan_dir
          paths:
            - tfplan
  apply:
    docker:
     - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: tfplan_dir
      - checkout
      - run: terraform init
      - run: terraform apply "tfplan_dir/tfplan" -auto-approve

workflows:
  version: 2
  validate_infra:
    jobs:
      - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master
